import { MessageCircle, Share2, ImagePlus, ThumbsUp } from 'lucide-react';
import { addPost, addComment, reactToPost, sharePost, deleteComment, deletePost } from './actions';
import { posts, comments, reactions } from '@/db/schema';
type Post=typeof posts.$inferSelect;
type Comment=typeof comments.$inferSelect;
type Reaction=typeof reactions.$inferSelect;
const choices=['👍','❤️','👏','🎉','😂'];
export default function BoardFeed({feed,commentList,reactionList,originals,shares,userId,userName,admin}:{feed:Post[];commentList:Comment[];reactionList:Reaction[];originals:Post[];shares:{sharedPostId:string|null}[];userId:string;userName:string;admin:boolean}){
 const originalMap=new Map([...feed,...originals].map(p=>[p.id,p]));
 return <div className="boardLayout"><div className="boardColumn"><form action={addPost} className="composer"><div className="composerHeader"><span className="avatar">{userName.slice(0,1).toUpperCase()}</span><label htmlFor="postBody">Share something with the team</label></div><textarea id="postBody" name="body" maxLength={2000} rows={3} placeholder="What’s happening? A job win, birthday, family update, or just a thought…"/><div className="composerFooter"><label className="photoPicker"><ImagePlus size={19}/> Add a photo<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"/></label><span>Photos up to 8 MB</span><button className="primary">Post</button></div></form>
 {feed.length===0&&<div className="feedEmpty"><h2>Nothing on the board yet</h2><p>Share an update and start the conversation.</p></div>}
 <div className="socialFeed">{feed.map(p=>{
 const relatedComments=commentList.filter(c=>c.postId===p.id),relatedReactions=reactionList.filter(r=>r.postId===p.id),mine=relatedReactions.find(r=>r.ownerId===userId),original=p.sharedPostId?originalMap.get(p.sharedPostId):null;
 return <article className="socialPost" key={p.id}><div className="socialPostHeader"><span className="avatar">{p.author.slice(0,1).toUpperCase()}</span><div className="socialIdentity"><strong>{p.author}</strong><small>{new Date(p.createdAt).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}{p.sharedPostId?' · Shared a post':''}</small></div>{admin&&<form action={deletePost}><input type="hidden" name="id" value={p.id}/><button className="textButton" aria-label={`Delete post by ${p.author}`}>Delete</button></form>}</div>
 {p.body&&<p className="socialBody">{p.body}</p>}
 {p.sharedPostId&&<div className="sharedPost">{original?<><div className="sharedAuthor"><span className="avatar small">{original.author.slice(0,1).toUpperCase()}</span><strong>{original.author}</strong></div>{original.body&&<p>{original.body}</p>}{original.imageKey&&<img src={`/api/board-photo?id=${original.id}`} alt={`Photo shared by ${original.author}`} loading="lazy"/>}</>:<p>This post is no longer available.</p>}</div>}
 {p.imageKey&&<img className="postPhoto" src={`/api/board-photo?id=${p.id}`} alt={`Photo shared by ${p.author}`} loading="lazy"/>}
 <div className="engagement"><span>{relatedReactions.length?`${[...new Set(relatedReactions.map(r=>r.emoji))].join(' ')} ${relatedReactions.length}`:'Be the first to react'}</span><span>{relatedComments.length} {relatedComments.length===1?'comment':'comments'} · {shares.filter(x=>x.sharedPostId===p.id).length} shares</span></div>
 <div className="postActions"><details className="reactionPicker"><summary><ThumbsUp size={18}/>{mine?`${mine.emoji} Reacted`:'React'}</summary><div className="reactionChoices">{choices.map(emoji=><form action={reactToPost} key={emoji}><input type="hidden" name="postId" value={p.id}/><button name="emoji" value={emoji} aria-label={`React ${emoji}`} className={mine?.emoji===emoji?'selected':''}>{emoji}</button></form>)}</div></details><a href={`#comment-${p.id}`}><MessageCircle size={18}/> Comment</a><details className="sharePanel"><summary><Share2 size={18}/> Share</summary><form action={sharePost}><input type="hidden" name="postId" value={p.id}/><label>Add a thought (optional)<input name="body" maxLength={500} placeholder="Say something about this post"/></label><button className="secondary">Share to team board</button></form></details></div>
 {relatedComments.length>0&&<div className="comments">{relatedComments.map(c=><div className="comment" key={c.id}><span className="avatar small">{c.author.slice(0,1).toUpperCase()}</span><div className="commentBubble"><strong>{c.author}</strong><p>{c.body}</p><small>{new Date(c.createdAt).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></div>{(admin||c.ownerId===userId)&&<form action={deleteComment}><input type="hidden" name="id" value={c.id}/><button className="textButton" aria-label={`Delete comment by ${c.author}`}>Delete</button></form>}</div>)}</div>}
 <form action={addComment} className="commentForm" id={`comment-${p.id}`}><span className="avatar small">{userName.slice(0,1).toUpperCase()}</span><input type="hidden" name="postId" value={p.id}/><input required name="body" maxLength={1000} aria-label={`Comment on ${p.author}'s post`} placeholder="Write a comment…"/><button>Post</button></form>
 </article>})}</div></div><aside className="boardAside"><div className="boardInfo"><span className="eyebrow">OUR TEAM SPACE</span><h2>Good things are better shared.</h2><p>Celebrate milestones, share a photo, and keep up with your teammates. Only approved team members can see this board.</p></div></aside></div>
}
