'use client';
import { useActionState, useState } from 'react';
import { updateTimeEntry, deleteTimeEntry } from './actions';
import { JOB_TASK_TYPES, billingForTask } from '@/lib/job-task-types';
import { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel } from '@/components/ui/alert-dialog';
import type { entries } from '@/db/schema';
export default function EditTimeEntry({entry}:{entry:typeof entries.$inferSelect}){
 const [taskType,setTaskType]=useState(JOB_TASK_TYPES.some(t=>t===entry.taskType)?entry.taskType!:'');
 const [state,action,pending]=useActionState(updateTimeEntry,{error:'',success:false});
 const [deleteState,deleteAction,deleting]=useActionState(deleteTimeEntry,{error:''});
 return <details className="editTime"><summary>Edit entry</summary><form action={action}><input type="hidden" name="id" value={entry.id}/><div className="formGrid"><label>Work date<input required type="date" name="date" defaultValue={entry.date}/></label><label>Hours<input required type="number" name="hours" min="0.01" max="24" step="0.01" defaultValue={entry.hours||''}/></label><label className="wide">Project / client / location<input required name="project" maxLength={150} defaultValue={entry.project||''}/></label><label>Job / task type<select required name="taskType" value={taskType} onChange={e=>setTaskType(e.target.value)}><option value="" disabled>Select a task type</option>{JOB_TASK_TYPES.map(task=><option key={task}>{task}</option>)}</select></label><div className="automaticBilling"><span>Billing</span><p className={taskType==='Administrative'?'billing muted':'billing'}>{!taskType?'Select a task':billingForTask(taskType)==='non-billable'?'Non-billable':'Billable'}</p></div></div>{state.error&&<p role="alert" className="timeWarning">{state.error}</p>}{state.success&&<p role="status" className="editSuccess">Correction saved. Daily totals are updated.</p>}<button className="primary" disabled={pending}>{pending?'Saving…':'Save correction'}</button></form><div className="deleteTimeArea"><AlertDialog><AlertDialogTrigger asChild><button type="button" className="deleteTimeButton">Delete entry</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this time entry?</AlertDialogTitle><AlertDialogDescription>This will remove {entry.hours?.toFixed(2)} hours for {entry.project||'this job'} on {entry.date} and update your daily total. This cannot be undone.</AlertDialogDescription></AlertDialogHeader><form action={deleteAction}><input type="hidden" name="id" value={entry.id}/>{deleteState.error&&<p role="alert" className="timeWarning">{deleteState.error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={deleting}>Keep entry</AlertDialogCancel><button type="submit" className="deleteTimeConfirm" disabled={deleting}>{deleting?'Deleting…':'Delete entry'}</button></AlertDialogFooter></form></AlertDialogContent></AlertDialog></div></details>
}
