import { desc, eq, inArray, and, gte, lte, sql } from 'drizzle-orm';
import {redirect} from 'next/navigation';
import {logout} from './auth-actions';
import AccountManager from './account-manager';
import AccountPanel from './account-panel';
import {database} from '@/lib/database.mjs';
import { currentMember } from '@/lib/portal';
import { getDb } from '@/db';
import { entries, posts, members, comments, reactions } from '@/db/schema';
import { submitEntry } from './actions';
import WebMCP from './webmcp';
import BoardFeed from './board-feed';
import TimesheetForm from './timesheet';
import PtoForm from './pto-form';
import PtoDecision from './pto-decision';
import ExpensePayment from './expense-payment';
import ExpenseForm from './expense-form';
import ExpenseHistory from './expense-history';
import { ptoDescription, ptoHoursInYear } from '@/lib/pto';
import TimesheetHistory from './timesheet-history';
import { workweekFor, workweekLabel } from '@/lib/workweek';
import { Clock3, CalendarDays, Receipt, BookOpen, MessageSquare, ShieldCheck, HeartHandshake, Hammer, LogOut } from 'lucide-react';
export const dynamic='force-dynamic';
export default async function Home({searchParams}:{searchParams:Promise<{view?:string}>}){
 const m=await currentMember();if(!m)redirect('/login');
 const params=await searchParams; const allowed=['home','time','expenses','pto','handbook','board','hr','admin','account'];const view=allowed.includes(params.view||'')?params.view!:'home';const db=getDb();const mine=await db.select().from(entries).where(eq(entries.ownerId,m.id)).orderBy(desc(entries.createdAt)).limit(30);const feed=await db.select().from(posts).orderBy(desc(posts.createdAt)).limit(50);const admin=m.role==='admin';const all=admin?await db.select().from(entries).orderBy(desc(entries.createdAt)).limit(100):[];const team=admin?await db.select().from(members).orderBy(desc(members.createdAt)):[];const feedIds=feed.map(p=>p.id);const commentList=view==='board'&&feedIds.length?await db.select().from(comments).where(inArray(comments.postId,feedIds)).orderBy(comments.createdAt):[];const reactionList=view==='board'&&feedIds.length?await db.select().from(reactions).where(inArray(reactions.postId,feedIds)):[];const originalIds=feed.map(p=>p.sharedPostId).filter((id):id is string=>!!id);const originals=view==='board'&&originalIds.length?await db.select().from(posts).where(inArray(posts.id,originalIds)):[];const shares=view==='board'&&feedIds.length?await db.select({sharedPostId:posts.sharedPostId}).from(posts).where(inArray(posts.sharedPostId,feedIds)):[];const timeRows=view==='time'?await db.select().from(entries).where(and(eq(entries.ownerId,m.id),eq(entries.kind,'time'))).orderBy(desc(entries.date),desc(entries.createdAt)).limit(240):[];const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const datePart=(key:string)=>parts.find(p=>p.type===key)?.value||'';const localToday=`${datePart('year')}-${datePart('month')}-${datePart('day')}`;const expenseRows=view==='expenses'?await db.select().from(entries).where(and(eq(entries.ownerId,m.id),eq(entries.kind,'expense'))).orderBy(desc(entries.createdAt)):[];const totalsByDate:Record<string,number>={};for(const row of timeRows)totalsByDate[row.date]=(totalsByDate[row.date]||0)+(row.hours||0);
 const workweek=workweekFor(localToday);
 const weeklyTotal=view==='time'?(await db.select({hours:sql<number>`coalesce(sum(${entries.hours}), 0)`}).from(entries).where(and(eq(entries.ownerId,m.id),eq(entries.kind,'time'),gte(entries.date,workweek.start),lte(entries.date,localToday))).get())?.hours||0:0;
 const ptoRows=view==='pto'?await db.select().from(entries).where(and(eq(entries.ownerId,m.id),eq(entries.kind,'pto'))).orderBy(desc(entries.date),desc(entries.createdAt)):[];
 const ptoYear=Number(localToday.slice(0,4));const approvedPto=ptoRows.filter(e=>e.status==='approved').reduce((sum,e)=>sum+ptoHoursInYear(e,ptoYear),0);const pendingPto=ptoRows.filter(e=>e.status==='submitted').reduce((sum,e)=>sum+ptoHoursInYear(e,ptoYear),0);
 const nav: Array<[string,string,typeof Hammer]>=[['home','Overview',Hammer],['time','Timesheets',Clock3],['expenses','Expenses',Receipt],['pto','Time off',CalendarDays],['handbook','Handbook',BookOpen],['board','Team board',MessageSquare],['hr','HR report',HeartHandshake],['account','My account',ShieldCheck],...(admin?([['admin','Admin',ShieldCheck]] as Array<[string,string,typeof Hammer]>):[])];
 const link=(v:string)=>`/?view=${v}`;
 const date=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});
 return <div className="shell"><WebMCP/><aside className="side"><a className="wordmark" href="/"><img className="brandLogo" src="/renovate-team-logo.png" alt="" width="48" height="48"/><span>THE RENOVATE TEAM<small>TEAM MEMBER PORTAL</small></span></a><div className="sideRule"/><nav aria-label="Main navigation">{nav.map(([key,label,Icon])=><a key={key} className={view===key?'active':''} href={link(key)}><Icon size={19}/>{label}</a>)}</nav><div className="sideFoot"><div className="avatar">{m.name.slice(0,1).toUpperCase()}</div><div><strong>{m.name}</strong><small>{admin?'Administrator':'Team member'}</small></div><form action={logout}><button className="textButton" aria-label="Sign out"><LogOut size={18}/></button></form></div></aside><div className="mainWrap"><header className="top"><div className="topBrand"><img src="/renovate-team-logo.png" alt="" width="30" height="30"/>THE RENOVATE TEAM <span>/ TEAM PORTAL</span></div><div className="topRight">{date}<span className="avatar small">{m.name.slice(0,1).toUpperCase()}</span></div></header><nav className="mobileNav" aria-label="Mobile navigation">{nav.map(([key,label,Icon])=><a key={key} href={link(key)} className={view===key?'active':''}><Icon size={19}/><span>{label}</span></a>)}</nav><main className="content">
 {view==='home'&&<><div className="heading"><span className="eyebrow">YOUR WORKSPACE</span><h1>Good morning, {m.name.split(' ')[0]}.</h1><p>Everything you need for the workweek, in one place.</p></div><div className="quickGrid"><a href={link('time')} className="quick dark"><Clock3/><span>LOG YOUR WORK</span><strong>Submit a timesheet</strong><small>Record hours and project details</small><b>→</b></a><a href={link('pto')} className="quick"><CalendarDays/><span>PLAN AHEAD</span><strong>Request time off</strong><small>Send dates for approval</small><b>→</b></a><a href={link('expenses')} className="quick"><Receipt/><span>KEEP IT SIMPLE</span><strong>Upload a receipt</strong><small>Track job expenses</small><b>→</b></a></div><div className="columns"><section className="panel"><div className="panelHead"><h2>Your recent activity</h2><a href={link('time')}>View records →</a></div>{mine.length?mine.slice(0,5).map(e=><div className="activity" key={e.id}><span className="activityIcon">{e.kind==='time'?'◷':e.kind==='pto'?'▦':e.kind==='expense'?'▧':'!'}</span><div><strong>{e.kind==='time'?`${e.hours} hours · ${e.project||'Work'}`:e.kind==='pto'?'Time off request':e.kind==='expense'?`Expense · $${e.amount?.toFixed(2)}`:'HR report'}</strong><small>{e.date}</small></div><em>{e.status}</em></div>):<p className="empty">Your submissions will appear here.</p>}</section><section className="panel"><div className="panelHead"><h2>From the team</h2><a href={link('board')}>Open board →</a></div>{feed.length?feed.slice(0,2).map(p=><div className="feedMini" key={p.id}><strong>{p.author}</strong><p>{p.body}</p></div>):<p className="empty">No posts yet. Share the first team update.</p>}</section></div></>}
 {view==='time'&&<><PageHead eyebrow="WORK HOURS" title="Timesheets" intro="Record each project or location you worked today. Your daily total adds up as you go."/><section className="weeklyHours" aria-label="Current workweek hours"><div><span className="eyebrow">THIS WORKWEEK</span><h2>Total Hours Worked</h2><p>{workweekLabel(workweek.start)} – {workweekLabel(workweek.end)}</p><small>Submitted work hours through today · Friday–Thursday</small></div><div className="weeklyHoursNumbers"><strong>{Number(weeklyTotal).toFixed(2)} <span>hours</span></strong>{Number(weeklyTotal)>40&&<div className="weeklyOvertime"><span>Overtime Worked</span><strong>{(Number(weeklyTotal)-40).toFixed(2)} <small>hours</small></strong></div>}</div></section><TimesheetForm today={localToday} totalsByDate={totalsByDate}/><TimesheetHistory rows={timeRows} today={localToday} employee={m.name}/></>}
 {view==='expenses'&&<><PageHead eyebrow="REIMBURSEMENTS" title="Expenses & receipts" intro="Submit a work expense and attach a photo or PDF of the receipt."/><ExpenseForm><input type="hidden" name="kind" value="expense"/><div className="formGrid"><label>Purchase date<input required type="date" name="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Amount ($)<input required type="number" name="amount" min="0.01" max="100000" step="0.01" placeholder="0.00"/></label><label className="wide">Project Name or Company Expense<input name="project" placeholder="Project or general company expense"/></label><label className="wide">Purchased from / Store<input name="merchant" maxLength={200} placeholder="e.g. Lowe’s — Owasso, or an online retailer"/></label><ExpensePayment/><label className="wide">Receipt (PDF or image, up to 10 MB)<input type="file" name="receipt" accept="image/jpeg,image/png,image/webp,application/pdf"/></label><label className="wide">Details<textarea name="note" rows={3} placeholder="What was purchased?"/></label></div></ExpenseForm><ExpenseHistory rows={expenseRows} today={localToday}/></>}
 {view==='pto'&&<><PageHead eyebrow="TIME AWAY" title="Request time off" intro="Request full days or a few hours off. You'll see the request status here."/><section className="panel ptoAnnual"><span className="eyebrow">CALENDAR YEAR {ptoYear}</span><h2>Your time off totals</h2><p>January 1 – December 31, {ptoYear}</p><div className="ptoAnnualTotals"><div><span>Total time off approved</span><strong>{approvedPto.toFixed(2)} <small>hours</small></strong></div><div><span>Total time off requested</span><strong>{(approvedPto+pendingPto).toFixed(2)} <small>hours</small></strong></div></div><small>Based on dates off in this calendar year. Full-day PTO counts as 8 hours per weekday; weekends are excluded. PTO hours do not apply to company-published paid holidays. Total requested includes approved and pending requests; declined requests are excluded. Check your paystub for your accrued PTO balance and time remaining.</small></section><PtoForm/><RecordList rows={ptoRows}/></>}
 {view==='handbook'&&<><PageHead eyebrow="TEAM RESOURCES" title="Team Member handbook" intro="Company policies and expectations will be available here."/><div className="formCard handbook"><BookOpen size={35}/><h2>Handbook coming soon</h2><p>The current team member handbook has not been provided for this portal yet. Ask Marc for the approved copy. This space is reserved for the official document and its revision date.</p></div></>}
 {view==='board'&&<><div className="boardHeading"><span className="eyebrow">TEAM CONNECTION</span><h1>Team board</h1><p>A place for what’s happening in work and life.</p></div><BoardFeed feed={feed} commentList={commentList} reactionList={reactionList} originals={originals} shares={shares} userId={m.id} userName={m.name} admin={admin}/></>}
 {view==='hr'&&<><PageHead eyebrow="CONFIDENTIAL" title="Share an HR concern" intro="Your report is visible only to the administrator. It will never appear on the team board."/><form action={submitEntry} className="formCard"><input type="hidden" name="kind" value="complaint"/><div className="formGrid"><label>Date of concern<input required type="date" name="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label className="wide">What happened?<textarea required name="note" maxLength={2000} rows={7} placeholder="Describe the concern and any follow-up you need."/></label></div><button className="primary">Send confidential report</button></form><RecordList rows={mine.filter(e=>e.kind==='complaint')}/></>}
 {view==='account'&&<AccountPanel/>}
 {view==='admin'&&admin&&<><PageHead eyebrow="ADMINISTRATION" title="Team administration" intro="Review submissions and approve team member access."/><AccountManager team={team.map(person=>({...person,username:(database().prepare('SELECT username FROM credentials WHERE member_id=?').get(person.id) as {username:string}|undefined)?.username}))} currentId={m.id}/><section className="panel adminPanel"><h2>Submissions</h2>{all.map(e=><div className="adminEntry" key={e.id}><div className="adminRow"><div><strong>{team.find(t=>t.id===e.ownerId)?.name||'Team member'} · {e.kind}</strong><small>{e.date}{e.endDate?` – ${e.endDate}`:''} · {e.status}</small></div>{e.kind==='pto'&&e.status==='submitted'&&<PtoDecision id={e.id}/>}</div>{e.kind==='pto'&&<><p className={e.status==='approved'?'ptoApproved':e.status==='declined'?'ptoDenied':''}>{ptoDescription(e)} · {e.status==='declined'?'Denied':e.status==='approved'?'Approved':'Pending approval'}</p>{e.denialReason&&<p className="ptoDenied denialReason"><strong>Reason for denial:</strong> {e.denialReason}</p>}</>}{e.kind==='time'&&<p>{e.hours} hours · {e.project} · {e.taskType||'Task not specified'} · {e.billingType||'Billing not marked'}</p>}{e.kind==='expense'&&<p>${e.amount?.toFixed(2)} · {e.project} {e.merchant&&<span> · Purchased from: {e.merchant}</span>} {e.companyCharge&&<strong className="reimbursementFlag">Company charge account · Bill needs to be entered</strong>} {e.reimbursement&&<strong className="reimbursementFlag">Reimbursement requested</strong>} {e.fileKey&&<a href={`/api/receipt?id=${e.id}`}>Download receipt</a>}</p>}{e.note&&<p>{e.note}</p>}</div>)}{!all.length&&<p className="empty">No submissions yet.</p>}</section></>}
 </main></div></div>
}
function PageHead({eyebrow,title,intro}:{eyebrow:string,title:string,intro:string}){return <div className="heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p></div>}
function RecordList({rows}:{rows:(typeof entries.$inferSelect)[]}){return <section className="panel records"><h2>Your submissions</h2>{rows.length?rows.map(e=><div className={`activity ${e.kind==='pto'?(e.status==='approved'?'ptoApproved':e.status==='declined'?'ptoDenied':''):''}`} key={e.id}><div><strong>{e.kind==='time'?`${e.hours} hours · ${e.project}`:e.kind==='expense'?`$${e.amount?.toFixed(2)} · ${e.project||'Expense'}`:e.kind==='pto'?ptoDescription(e):`Report · ${e.date}`}</strong><small>{e.date}{e.kind==='expense'&&e.merchant&&<> · {e.merchant}</>}{e.kind==='expense'&&e.companyCharge&&<> · Company charge account · Bill needs to be entered</>}{e.kind==='expense'&&e.reimbursement&&<> · Reimbursement requested</>}{e.fileKey&&<> · <a href={`/api/receipt?id=${e.id}`}>Receipt</a></>}</small>{e.kind==='pto'&&e.denialReason&&<p className="denialReason"><strong>Reason for denial:</strong> {e.denialReason}</p>}</div><em>{e.kind==='pto'?(e.status==='approved'?'Approved':e.status==='declined'?'Denied':'Pending approval'):e.status}</em></div>):<p className="empty">No submissions yet.</p>}</section>}
