import {test} from 'node:test';
import assert from 'node:assert/strict';
import Database from 'better-sqlite3';
import {hashPassword,verifyPassword,username,newToken,digest,memberForToken,issuePasswordLink,consumePasswordLink,limited} from '../lib/auth-core.mjs';
function db(){const d=new Database(':memory:');d.exec(`CREATE TABLE members(id TEXT PRIMARY KEY,name TEXT,email TEXT,role TEXT);CREATE TABLE credentials(member_id TEXT PRIMARY KEY,username TEXT UNIQUE,password_hash TEXT);CREATE TABLE sessions(digest TEXT PRIMARY KEY,member_id TEXT,expires_at INTEGER);CREATE TABLE password_links(digest TEXT PRIMARY KEY,member_id TEXT,expires_at INTEGER);CREATE TABLE login_limits(key TEXT PRIMARY KEY,attempts INTEGER,reset_at INTEGER);INSERT INTO members VALUES ('original-id','Marc','marc@renovateteam.com','admin'),('employee-a','A','a@test.local','employee'),('employee-b','B','b@test.local','employee');INSERT INTO credentials(member_id,username) VALUES ('original-id','marc'),('employee-a','alpha'),('employee-b','bravo');`);return d;}
test('password hashes are salted and reject incorrect or malformed values',async()=>{const password='correct horse battery staple';const a=await hashPassword(password),b=await hashPassword(password);assert.notEqual(a,b);assert.equal(await verifyPassword(password,a),true);assert.equal(await verifyPassword('wrong password',a),false);assert.equal(await verifyPassword(password,null),false);await assert.rejects(hashPassword('short'));});
test('username normalization does not allow spoofing or invalid identifiers',()=>{assert.equal(username(' Marc.Wells '),'marc.wells');assert.throws(()=>username('a'));assert.throws(()=>username('<script>'));});
test('setup preserves member identity, consumes token once and revokes all sessions',async()=>{const d=db();const previous=newToken();d.prepare('INSERT INTO sessions VALUES (?,?,?)').run(digest(previous),'original-id',Date.now()+100000);const token=issuePasswordLink(d,'original-id');assert.equal(d.prepare('SELECT digest FROM password_links').get().digest.includes(token),false);await consumePasswordLink(d,token,'my long test password');assert.equal(d.prepare('SELECT member_id FROM credentials WHERE username=?').get('marc').member_id,'original-id');assert.equal(d.prepare('SELECT count(*) n FROM sessions').get().n,0);await assert.rejects(consumePasswordLink(d,token,'another long test password'));});
test('expired, replaced and disabled-account password links cannot be used',async()=>{const d=db();const first=issuePasswordLink(d,'employee-a'),second=issuePasswordLink(d,'employee-a');await assert.rejects(consumePasswordLink(d,first,'my long test password'));d.prepare('UPDATE password_links SET expires_at=0').run();await assert.rejects(consumePasswordLink(d,second,'my long test password'));const third=issuePasswordLink(d,'employee-a');d.prepare("UPDATE members SET role='disabled' WHERE id='employee-a'").run();await assert.rejects(consumePasswordLink(d,third,'my long test password'));});
test('sessions isolate identities and reject forged, expired and disabled access',async()=>{const d=db();d.prepare('UPDATE credentials SET password_hash=?').run(await hashPassword('my long test password'));const a=newToken(),b=newToken();for(const [token,id] of [[a,'employee-a'],[b,'employee-b']])d.prepare('INSERT INTO sessions VALUES (?,?,?)').run(digest(token),id,Date.now()+100000);assert.equal(memberForToken(d,a).id,'employee-a');assert.equal(memberForToken(d,b).id,'employee-b');assert.equal(memberForToken(d,newToken()),null);assert.equal(memberForToken(d,a,Date.now()+200000),null);d.prepare("UPDATE members SET role='disabled' WHERE id='employee-a'").run();assert.equal(memberForToken(d,a),null);assert.equal(memberForToken(d,b).id,'employee-b');});
test('failed sign-in throttling expires and is stored in the database',()=>{const d=db();for(let i=0;i<10;i++)assert.equal(limited(d,'login:alpha',1000),false);assert.equal(limited(d,'login:alpha',1001),true);assert.equal(limited(d,'login:alpha',901001),false);});
